### ISSUE TITLE
Pull down to refresh has two loading spinners

### ISSUE THREAD

**Issue by piotrgajcy** [gdgradzymin/ngPolandConfNext#97]

**Comment by Abhijeet-sonkar** [comment]
@piotrgajcy  Can I work on this issue?

**Comment by sebastiandenis** [comment]
> @piotrgajcy Can I work on this issue?

@Abhijeet-sonkar thank you for your willingness to help. Currently, we're working hard to deliver the production version before the ngPoland and jsPoland events. The schedule is tight and we have an internal team for dealing with all issues before the first release. But after the first release, we're open to any help. And If you have any improvements that we could implement, we're also open to seeing your PR's. But please tell us about your plans upfront - just to be sure that this match with our roadmap.
